Repository redBorder/redborder-manager, pull requests merged in 2023-12, with the labels that each got.

#97 Improvement/#15878 rb selinux
  resources/bin/rb_bootstrap_common.sh
  resources/bin/rb_configure_initial_postgresql.sh
  resources/bin/rb_configure_leader.sh
  resources/chef/solo/rb-selinux-attributes.json
  resources/chef/solo/rb-selinux-solo.rb
Labels: kind/bug, size/S

#104 Change listCookbooks order
  resources/bin/rb_configure_leader.sh
Labels: size/XS, kind/documentation

#105 release 1.0.4
  packaging/rpm/redborder-manager.spec
Labels: size/XS, kind/documentation

#106 Add logstatter as dependency and upload logstatter cookbook in configure leader
  packaging/rpm/redborder-manager.spec
  resources/bin/rb_configure_leader.sh
Labels: size/XS, kind/feature

#107 Release 1.0.5
  packaging/rpm/redborder-manager.spec
Labels: size/XS, kind/documentation
