Repository redBorder/redborder-manager, pull requests merged in 2023-11, with the labels that each got.

#84 Rhel9
  README.md
  packaging/rpm/redborder-manager.spec
  resources/bin/rb_check
  resources/bin/rb_configure_initial_postgresql.sh
  resources/bin/rb_configure_initial_s3.sh
  resources/bin/rb_configure_leader.sh
  resources/bin/rb_create_rabbitusers.sh
  resources/bin/rb_psql
  resources/bin/rb_rabbitmq_rotate_logs.sh
  resources/bin/rb_synthetic_producer.rb
  resources/check/chef/rb_check_chef.rb
  resources/check/kafka/rb_check_kafka.rb
  resources/chef/role/cisco-cloudproxy.json
  resources/chef/role/exporter-sensor.json
  resources/chef/role/gateway-sensor.json
  resources/chef/role/ips-sensor.json
  resources/chef/role/ipscp-sensor.json
  resources/chef/role/ipsv2-sensor.json
  resources/chef/role/manager.json
  resources/chef/role/manager_node.json
  resources/chef/role/proxy-sensor.json
  resources/chef/role/social-sensor.json
  resources/scripts/rb_backup_node.rb
  resources/scripts/rb_camus_import.rb
  resources/scripts/rb_create_nginx_certs.rb
  resources/scripts/rb_get_logstash_stats.rb
  resources/scripts/rb_get_tasks.rb
  resources/scripts/rb_get_tiers.rb
  resources/scripts/rb_init_chef.rb
  resources/scripts/rb_init_conf.rb
  resources/scripts/rb_set_modules.rb
  resources/scripts/rb_setup_wizard.rb
Labels: kind/bug, size/L

#86 Feature/#15799 add network scripts
  packaging/rpm/redborder-manager.spec
  resources/scripts/rb_init_conf.rb
Labels: size/XS, kind/feature

#85 make rsa compatible with older versions
  resources/bin/rb_create_rsa.sh
Labels: size/XS, kind/bug

#88 Add new condition
  resources/lib/rb_wiz_lib.rb
Labels: size/XS, kind/feature

#89 Bump version 0.9.5
  packaging/rpm/redborder-manager.spec
Labels: size/XS, kind/feature

#91 replace --direct firewall rules
  packaging/rpm/redborder-manager.spec
  resources/scripts/rb_init_conf.rb
Labels: kind/bug, size/M

#90 Add dhclient package
  packaging/rpm/redborder-manager.spec
Labels: size/XS, kind/feature

#92 Release 0.9.6
  packaging/rpm/redborder-manager.spec
Labels: size/XS, kind/documentation

#94 make changes for sync_net config
  resources/lib/rb_config_utils.rb
  resources/scripts/rb_init_conf.rb
Labels: kind/bug, size/M

#98 fix default route
  resources/scripts/rb_init_conf.rb
Labels: kind/bug, size/S

#100 fix default route for 1 interface
  resources/scripts/rb_init_conf.rb
Labels: kind/bug, size/S

#101 Update redborder-manager.spec
  packaging/rpm/redborder-manager.spec
Labels: size/XS, kind/bug

#96 Add cgroup v2 capabilities to RedBorder NG
  packaging/rpm/redborder-manager.spec
  resources/bin/rb_configure_custom.sh
  resources/bin/rb_configure_leader.sh
Labels: kind/feature, size/S

#102 Release 1.0.0
  packaging/rpm/redborder-manager.spec
Labels: size/XS, kind/documentation

#103 add broadcoast port for public zone
  resources/scripts/rb_init_conf.rb
Labels: size/XS, kind/documentation
