Repository redBorder/redborder-manager, pull requests merged in 2024-05, with the labels that each got.

#119 change of kernel logging in terminal
  packaging/rpm/redborder-manager.spec
Labels: size/XS

#121 Release 1.1.0
  README.md
  VERSION
  packaging/rpm/redborder-manager.spec
Labels: kind/documentation, size/S

#118 add cookbook-rb-postfix to list of cookbooks
  resources/bin/rb_configure_leader.sh
Labels: size/XS, kind/documentation

#122 Release 1.2.0
  VERSION
  resources/bin/rb_configure_leader.sh
Labels: size/XS, kind/documentation

#120 Improvements/add runtime to configure leader and custom script
  resources/bin/rb_configure_custom.sh
  resources/bin/rb_configure_leader.sh
Labels: enhancement, kind/feature, size/S

#124 Add rb-common cookbook
  resources/bin/rb_configure_leader.sh
Labels: feature, size/XS, kind/feature

#125 Release 1.3.0
  VERSION
  resources/bin/rb_configure_custom.sh
  resources/bin/rb_configure_leader.sh
Labels: kind/feature, size/S
