Repository redBorder/redborder-manager, pull requests merged in 2024-04, with the labels that each got.

#114 add rb-exporter cookbook in the list of cookbooks to upload
  resources/bin/rb_configure_leader.sh
Labels: size/XS

#115 Release 1.0.9
  .github/workflows/rpm.yml
  VERSION
  resources/bin/rb_configure_leader.sh
Labels: kind/documentation, size/M

#116 Bug #17092: Skip routes configuration for interfaces without an ip
  resources/scripts/rb_init_conf.rb
Labels: size/XS

#117 Release 1.0.10
  VERSION
  resources/scripts/rb_init_conf.rb
Labels: size/XS, kind/documentation
