Repository redBorder/redborder-manager, pull requests merged in 2024-08, with the labels that each got.

#156 Add Mitre scripts
  packaging/rpm/redborder-manager.spec
  resources/tools/mitre.py
Labels: feature

#153 Feature/18013 integrate mongodb
  resources/scripts/rb_init_conf.rb
Labels: kind/feature

#144 Modify ips sensor role for ssh version of IPS
  resources/chef/role/ips-sensor.json
Labels: size/XS, kind/feature

#149 Add chrony cookbook to cookbook upload list
  resources/bin/rb_upload_cookbooks.sh
  resources/scripts/rb_init_conf.rb
Labels: size/XS
