Repository redBorder/redborder-manager, pull requests merged in 2024-01, with the labels that each got.

#108 adding rb-arubacentral
  resources/bin/rb_configure_leader.sh
  resources/chef/role/arubacentral-sensor.json
Labels: kind/feature, size/S

#110 Release 1.0.6
  packaging/rpm/redborder-manager.spec
Labels: size/XS, kind/documentation

#109 PR 109 - Add positiblity to custom set Storage value of journald configuration
  resources/scripts/rb_set_journald_storage.rb
Labels: kind/feature, size/M

#111 Release 1.0.7
  packaging/rpm/redborder-manager.spec
Labels: size/XS, kind/documentation
