Repository redBorder/redborder-manager, pull requests merged in 2024-07, with the labels that each got.

#146 fix case when no static interface is selected
  resources/scripts/rb_setup_wizard.rb
Labels: kind/bug, size/S

#145 Release 2.2.3
  VERSION
  resources/scripts/rb_setup_wizard.rb
  resources/scripts/rb_sync_minio_cluster.rb
Labels: size/XS, kind/documentation

#147 Feature/incident response
  resources/bin/rb_configure_leader.sh
Labels: size/XS, kind/feature

#151 Generate random 128 bit serial for ssl cert
  resources/scripts/rb_create_nginx_certs.rb
Labels: size/XS

#155 Release 2.3.1
  VERSION
  resources/scripts/rb_create_nginx_certs.rb
Labels: size/XS
