Repository redBorder/redborder-manager, pull requests merged in 2024-06, with the labels that each got.

#128 Allow user to specify the management interface
  resources/scripts/rb_init_conf.rb
  resources/scripts/rb_setup_wizard.rb
Labels: kind/feature, size/M

#131 Release 1.3.1
  VERSION
  resources/scripts/rb_init_conf.rb
  resources/scripts/rb_setup_wizard.rb
Labels: enhancement, size/M

#127 Bugfix/#16981 fix wakeup chef cluster
  resources/bin/rb_wakeup_chef.sh
Labels: size/XS, kind/bug

#132 Release 1.3.2
  VERSION
  resources/bin/rb_wakeup_chef.sh
Labels: size/XS, kind/documentation

#126 Minio FailOver support (s3 cluster mode)
  resources/bin/rb_configure_initial_s3.sh
  resources/bin/rb_sync_minio_cluster.sh
  resources/scripts/rb_sync_minio_cluster.rb
Labels: size/L, kind/feature

#133 release 2.0.0
  VERSION
  resources/bin/rb_configure_initial_s3.sh
  resources/bin/rb_sync_minio_cluster.sh
  resources/scripts/rb_sync_minio_cluster.rb
Labels: size/L, kind/documentation

#135 Change red.rb to rbcli.rb
  resources/bin/rb_refresh_darklist_memcached_keys.sh
Labels: size/XS, kind/documentation

#134 Release 2.0.1
  VERSION
  resources/bin/rb_refresh_darklist_memcached_keys.sh
  resources/scripts/rb_init_conf.rb
Labels: size/XS, kind/feature, kind/documentation

#136 Release 2.1.0
  VERSION
  resources/bin/rb_checkping.sh
  resources/bin/rb_checkudp.sh
  resources/bin/rb_configure_leader.sh
  resources/bin/rb_create_lo.sh
  resources/scripts/rb_init_conf.rb
Labels: size/L, kind/documentation

#137 Add ClamAV to upload list
  resources/bin/rb_configure_leader.sh
Labels: size/XS, kind/feature

#140 Release 2.2.0
  VERSION
  resources/bin/rb_configure_leader.sh
  resources/check/memcached/rb_check_memcached.rb
Labels: kind/documentation, size/S

#138 Fix management detection when only one iface
  resources/scripts/rb_setup_wizard.rb
Labels: kind/bug, size/S

#141 Fix management interface configuration in case there is only one interface
  VERSION
  resources/scripts/rb_setup_wizard.rb
Labels: kind/bug, size/S

#139 Add memcached ports to the firewall, udp and tcp
  resources/scripts/rb_init_conf.rb
Labels: size/XS, kind/feature

#143 Release 2.2.2
  VERSION
  resources/scripts/rb_init_conf.rb
Labels: size/XS, kind/documentation
